variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SCRIPTS_REPO: https://$SCRIPTS_USER:$SCRIPTS_TOKEN@gitlab.com/vertafore/agency/sdet/ci-scripts.git

image: openjdk:11-jdk-slim

stages:
  - project checks
  - test
  - report

build:
  tags: [ Windows ]
  stage: project checks
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - ./gradlew --build-cache build testClasses -x test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build

spotless:
  tags: [ Windows ]
  stage: project checks
  script:
    - ./gradlew spotlessJavaCheck
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
      - "**/*.java"

.windows scripts:
  tags: [Windows]
  before_script:
    - Write-Host $CI_RUNNER_TAGS
    - if (Test-Path ./scripts) { Remove-Item ./scripts -Recurse -Force }
    - mkdir scripts
    - git clone "$SCRIPTS_REPO" "./scripts"
    - Get-ChildItem ./scripts -Filter "*.psm1" | ForEach { Import-Module $_.FullName }

.run_tc_from_branch:
  tags: [ Windows ]
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  extends: .windows scripts
  script:
    - echo "$CI_MERGE_REQUEST_TITLE"
    - Import-Module .\lib\scripts\findAndFormatTests.ps1
    - $TestCases = Find-TestCases -MergeRequestTitle $CI_MERGE_REQUEST_TITLE
    - echo "$TestCases"
    - ./gradlew testClasses test ($TestCases -Split " ") --info
  dependencies: [ ]

.regression:
  tags: [ Windows ]
  stage: test
  extends: .windows scripts
  rules:
    - if: ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web")
  script:
    - Set-ReportPortalProperties -Project EMS -LaunchName $LAUNCH_NAME
    - echo $ENVIRONMENT
    - ./gradlew testClasses test --info -Denvironment="$ENVIRONMENT"
  interruptible: false

QA:
  extends: .run_tc_from_branch

QA Regression:
  extends: .regression
  rules:
    - if: $ENVIRONMENT == "QA"

MDC Regression:
  extends: .regression
  rules:
    - if: $ENVIRONMENT == "MDC"

report:
  stage: report
  extends: .windows scripts
  script:
    - cd scripts
    - npm install
    - python SendResults_EMS.py ems
  rules:
    - if: ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web")
  retry: 2
  dependencies: []
  