variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SCRIPTS_REPO: https://$SCRIPTS_USER:$SCRIPTS_TOKEN@gitlab.com/vertafore/agency/sdet/ci-scripts.git

image: openjdk:11-jdk-slim

stages:
  - project checks
  - test

build:
  tags: [ Windows ]
  stage: project checks
  only:
    - merge_requests
  script:
    - ./gradlew --build-cache build testClasses -x test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build

spotless:
  tags: [ Windows ]
  stage: project checks
  script:
    - ./gradlew spotlessJavaCheck
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.java"

.windows scripts:
  tags: [Windows]
  before_script:
    - Write-Host $CI_RUNNER_TAGS
    - if (Test-Path ./scripts) { Remove-Item ./scripts -Recurse -Force }
    - mkdir scripts
    - git clone "$SCRIPTS_REPO" "./scripts"
    - Get-ChildItem ./scripts -Filter "*.psm1" | ForEach { Import-Module $_.FullName }

.run_tc_from_branch:
  tags: [ Windows ]
  stage: test
  only:
    - merge_requests
  extends: .windows scripts
  script:
    - echo "$CI_MERGE_REQUEST_TITLE"
    - Import-Module .\lib\scripts\findAndFormatTests.ps1
    - $TestCases = Find-TestCases -MergeRequestTitle $CI_MERGE_REQUEST_TITLE
    - echo "$TestCases"
    - ./gradlew testClasses test ($TestCases -Split " ") --info
  dependencies: [ ]

.regression:
  tags: [ Windows ]
  stage: test
  only:
    - schedules
    - web
  extends: .windows scripts
  script:
    - Set-ReportPortalProperties -Project EMS -LaunchName $LAUNCH_NAME
    - ./gradlew testClasses test --info
  interruptible: false

QA:
  extends: .run_tc_from_branch

QA Regression:
  extends: .regression

MDC Regression:
  extends: .regression