/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AssignedRoleCountV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class AssignedRoleCountV1 {
  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("roleIds")
  private List<String> roleIds = new ArrayList<String>();

  @SerializedName("userStatus")
  private String userStatus = null;

  @SerializedName("assignedRoleCount")
  private Integer assignedRoleCount = null;

   /**
   * Id of tenant context for users assigned roles that are included in the count
   * @return tenantId
  **/
  @ApiModelProperty(example = "exampleTenant", required = true, value = "Id of tenant context for users assigned roles that are included in the count")
  public String getTenantId() {
    return tenantId;
  }

   /**
   * Id of entity context for users assigned roles that are included in the count
   * @return entityId
  **/
  @ApiModelProperty(example = "exampleEntityId", required = true, value = "Id of entity context for users assigned roles that are included in the count")
  public String getEntityId() {
    return entityId;
  }

  public AssignedRoleCountV1 roleIds(List<String> roleIds) {
    this.roleIds = roleIds;
    return this;
  }

  public AssignedRoleCountV1 addRoleIdsItem(String roleIdsItem) {
    this.roleIds.add(roleIdsItem);
    return this;
  }

   /**
   * Role ids included in the count
   * @return roleIds
  **/
  @ApiModelProperty(example = "\"['UUID1', 'UUID2']\"", required = true, value = "Role ids included in the count")
  public List<String> getRoleIds() {
    return roleIds;
  }

  public void setRoleIds(List<String> roleIds) {
    this.roleIds = roleIds;
  }

  public AssignedRoleCountV1 userStatus(String userStatus) {
    this.userStatus = userStatus;
    return this;
  }

   /**
   * Status of users to include, true for only active users, false for only inactive user and all for all 
   * @return userStatus
  **/
  @ApiModelProperty(example = "true", required = true, value = "Status of users to include, true for only active users, false for only inactive user and all for all ")
  public String getUserStatus() {
    return userStatus;
  }

  public void setUserStatus(String userStatus) {
    this.userStatus = userStatus;
  }

   /**
   * Number of assigned roles
   * @return assignedRoleCount
  **/
  @ApiModelProperty(value = "Number of assigned roles")
  public Integer getAssignedRoleCount() {
    return assignedRoleCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignedRoleCountV1 assignedRoleCountV1 = (AssignedRoleCountV1) o;
    return Objects.equals(this.tenantId, assignedRoleCountV1.tenantId) &&
        Objects.equals(this.entityId, assignedRoleCountV1.entityId) &&
        Objects.equals(this.roleIds, assignedRoleCountV1.roleIds) &&
        Objects.equals(this.userStatus, assignedRoleCountV1.userStatus) &&
        Objects.equals(this.assignedRoleCount, assignedRoleCountV1.assignedRoleCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, entityId, roleIds, userStatus, assignedRoleCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignedRoleCountV1 {\n");
    
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    roleIds: ").append(toIndentedString(roleIds)).append("\n");
    sb.append("    userStatus: ").append(toIndentedString(userStatus)).append("\n");
    sb.append("    assignedRoleCount: ").append(toIndentedString(assignedRoleCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

