/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import modelPackage.ComputedAuthenticationSettingsV1;
import org.threeten.bp.OffsetDateTime;

/**
 * AuthenticationSettingsV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class AuthenticationSettingsV1 {
  @SerializedName("mfaEnabled")
  private Boolean mfaEnabled = null;

  @SerializedName("createdOn")
  private OffsetDateTime createdOn = null;

  @SerializedName("updatedOn")
  private OffsetDateTime updatedOn = null;

  @SerializedName("computed")
  private ComputedAuthenticationSettingsV1 computed = null;

  public AuthenticationSettingsV1 mfaEnabled(Boolean mfaEnabled) {
    this.mfaEnabled = mfaEnabled;
    return this;
  }

   /**
   * Boolean value indicating if MFA is required for users accessing this product/tenant/entity
   * @return mfaEnabled
  **/
  @ApiModelProperty(example = "false", value = "Boolean value indicating if MFA is required for users accessing this product/tenant/entity")
  public Boolean isMfaEnabled() {
    return mfaEnabled;
  }

  public void setMfaEnabled(Boolean mfaEnabled) {
    this.mfaEnabled = mfaEnabled;
  }

   /**
   * instant these settings were created
   * @return createdOn
  **/
  @ApiModelProperty(value = "instant these settings were created")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

   /**
   * instant these settings were last modified
   * @return updatedOn
  **/
  @ApiModelProperty(value = "instant these settings were last modified")
  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }

   /**
   * Computed settings for the requested context
   * @return computed
  **/
  @ApiModelProperty(value = "Computed settings for the requested context")
  public ComputedAuthenticationSettingsV1 getComputed() {
    return computed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationSettingsV1 authenticationSettingsV1 = (AuthenticationSettingsV1) o;
    return Objects.equals(this.mfaEnabled, authenticationSettingsV1.mfaEnabled) &&
        Objects.equals(this.createdOn, authenticationSettingsV1.createdOn) &&
        Objects.equals(this.updatedOn, authenticationSettingsV1.updatedOn) &&
        Objects.equals(this.computed, authenticationSettingsV1.computed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mfaEnabled, createdOn, updatedOn, computed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationSettingsV1 {\n");
    
    sb.append("    mfaEnabled: ").append(toIndentedString(mfaEnabled)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    computed: ").append(toIndentedString(computed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

