/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AuthUserContextV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class AuthUserContextV1 {
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("tenantId")
  private String tenantId = null;

   /**
   * active status of entity context assignment
   * @return active
  **/
  @ApiModelProperty(example = "false", value = "active status of entity context assignment")
  public Boolean isActive() {
    return active;
  }

   /**
   * Id of entity context for assignment
   * @return entityId
  **/
  @ApiModelProperty(value = "Id of entity context for assignment")
  public String getEntityId() {
    return entityId;
  }

   /**
   * Id of tenant context for assignment
   * @return tenantId
  **/
  @ApiModelProperty(value = "Id of tenant context for assignment")
  public String getTenantId() {
    return tenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthUserContextV1 authUserContextV1 = (AuthUserContextV1) o;
    return Objects.equals(this.active, authUserContextV1.active) &&
        Objects.equals(this.entityId, authUserContextV1.entityId) &&
        Objects.equals(this.tenantId, authUserContextV1.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, entityId, tenantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthUserContextV1 {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

