/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * AuthGroupV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class AuthGroupV1 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("createdOn")
  private OffsetDateTime createdOn = null;

  @SerializedName("updatedOn")
  private OffsetDateTime updatedOn = null;

  @SerializedName("deletedOn")
  private OffsetDateTime deletedOn = null;

  @SerializedName("description")
  private String description = null;

  /**
   * Gets or Sets groupCreationSource
   */
  @JsonAdapter(GroupCreationSourceEnum.Adapter.class)
  public enum GroupCreationSourceEnum {
    FEDERATED("federated"),
    
    UNFEDERATED("unfederated");

    private String value;

    GroupCreationSourceEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GroupCreationSourceEnum fromValue(String text) {
      for (GroupCreationSourceEnum b : GroupCreationSourceEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<GroupCreationSourceEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GroupCreationSourceEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GroupCreationSourceEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return GroupCreationSourceEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("groupCreationSource")
  private GroupCreationSourceEnum groupCreationSource = null;

  @SerializedName("sourceAclId")
  private String sourceAclId = null;

   /**
   * Unique id of the AuthGroup
   * @return id
  **/
  @ApiModelProperty(example = "b647a79e-b500-4640-a1bf-2aeb2efef379", value = "Unique id of the AuthGroup")
  public String getId() {
    return id;
  }

  public AuthGroupV1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A human-readable name for the AuthGroup.
   * @return name
  **/
  @ApiModelProperty(example = "Managers", required = true, value = "A human-readable name for the AuthGroup.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

   /**
   * When the AuthGroup was created
   * @return createdOn
  **/
  @ApiModelProperty(value = "When the AuthGroup was created")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

   /**
   * When the AuthGroup was last modified
   * @return updatedOn
  **/
  @ApiModelProperty(value = "When the AuthGroup was last modified")
  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }

   /**
   * When the AuthGroup was deleted
   * @return deletedOn
  **/
  @ApiModelProperty(value = "When the AuthGroup was deleted")
  public OffsetDateTime getDeletedOn() {
    return deletedOn;
  }

  public AuthGroupV1 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description for the AuthGroup.
   * @return description
  **/
  @ApiModelProperty(example = "Admins for the system", value = "A description for the AuthGroup.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AuthGroupV1 groupCreationSource(GroupCreationSourceEnum groupCreationSource) {
    this.groupCreationSource = groupCreationSource;
    return this;
  }

   /**
   * Get groupCreationSource
   * @return groupCreationSource
  **/
  @ApiModelProperty(value = "")
  public GroupCreationSourceEnum getGroupCreationSource() {
    return groupCreationSource;
  }

  public void setGroupCreationSource(GroupCreationSourceEnum groupCreationSource) {
    this.groupCreationSource = groupCreationSource;
  }

  public AuthGroupV1 sourceAclId(String sourceAclId) {
    this.sourceAclId = sourceAclId;
    return this;
  }

   /**
   * An access control list for the AuthGroup.
   * @return sourceAclId
  **/
  @ApiModelProperty(example = "Source ACL ID", value = "An access control list for the AuthGroup.")
  public String getSourceAclId() {
    return sourceAclId;
  }

  public void setSourceAclId(String sourceAclId) {
    this.sourceAclId = sourceAclId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthGroupV1 authGroupV1 = (AuthGroupV1) o;
    return Objects.equals(this.id, authGroupV1.id) &&
        Objects.equals(this.name, authGroupV1.name) &&
        Objects.equals(this.createdOn, authGroupV1.createdOn) &&
        Objects.equals(this.updatedOn, authGroupV1.updatedOn) &&
        Objects.equals(this.deletedOn, authGroupV1.deletedOn) &&
        Objects.equals(this.description, authGroupV1.description) &&
        Objects.equals(this.groupCreationSource, authGroupV1.groupCreationSource) &&
        Objects.equals(this.sourceAclId, authGroupV1.sourceAclId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, createdOn, updatedOn, deletedOn, description, groupCreationSource, sourceAclId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthGroupV1 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    deletedOn: ").append(toIndentedString(deletedOn)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    groupCreationSource: ").append(toIndentedString(groupCreationSource)).append("\n");
    sb.append("    sourceAclId: ").append(toIndentedString(sourceAclId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

