/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ComputedAuthenticationSettingsV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class ComputedAuthenticationSettingsV1 {
  @SerializedName("mfaEnabled")
  private Boolean mfaEnabled = null;

   /**
   * Computed Boolean value indicating if MFA is required for users accessing this product/tenant/entity
   * @return mfaEnabled
  **/
  @ApiModelProperty(example = "false", value = "Computed Boolean value indicating if MFA is required for users accessing this product/tenant/entity")
  public Boolean isMfaEnabled() {
    return mfaEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComputedAuthenticationSettingsV1 computedAuthenticationSettingsV1 = (ComputedAuthenticationSettingsV1) o;
    return Objects.equals(this.mfaEnabled, computedAuthenticationSettingsV1.mfaEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mfaEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComputedAuthenticationSettingsV1 {\n");
    
    sb.append("    mfaEnabled: ").append(toIndentedString(mfaEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

