/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import modelPackage.AuthorizationInfoV1;
import modelPackage.VertaforeUserV1;

/**
 * ContextualAuthInfoV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class ContextualAuthInfoV1 {
  @SerializedName("authz")
  private AuthorizationInfoV1 authz = null;

  @SerializedName("user")
  private VertaforeUserV1 user = null;

  public ContextualAuthInfoV1 authz(AuthorizationInfoV1 authz) {
    this.authz = authz;
    return this;
  }

   /**
   * Get authz
   * @return authz
  **/
  @ApiModelProperty(value = "")
  public AuthorizationInfoV1 getAuthz() {
    return authz;
  }

  public void setAuthz(AuthorizationInfoV1 authz) {
    this.authz = authz;
  }

  public ContextualAuthInfoV1 user(VertaforeUserV1 user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public VertaforeUserV1 getUser() {
    return user;
  }

  public void setUser(VertaforeUserV1 user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextualAuthInfoV1 contextualAuthInfoV1 = (ContextualAuthInfoV1) o;
    return Objects.equals(this.authz, contextualAuthInfoV1.authz) &&
        Objects.equals(this.user, contextualAuthInfoV1.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authz, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextualAuthInfoV1 {\n");
    
    sb.append("    authz: ").append(toIndentedString(authz)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

