/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EntityConcordanceV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class EntityConcordanceV1 {
  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("realmName")
  private String realmName = null;

  @SerializedName("sourceEntityId")
  private String sourceEntityId = null;

  /**
   * Type of Source
   */
  @JsonAdapter(SourceTypeEnum.Adapter.class)
  public enum SourceTypeEnum {
    SAGITTA("SAGITTA"),
    
    AMS360("AMS360"),
    
    QQ("QQ");

    private String value;

    SourceTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SourceTypeEnum fromValue(String text) {
      for (SourceTypeEnum b : SourceTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SourceTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SourceTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SourceTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SourceTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("sourceType")
  private SourceTypeEnum sourceType = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  public EntityConcordanceV1 entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Id of the Entity
   * @return entityId
  **/
  @ApiModelProperty(example = "b647a79e-b500-4640-a1bf-2aeb2efef379", required = true, value = "Id of the Entity")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

   /**
   * Displayable name of the Realm
   * @return realmName
  **/
  @ApiModelProperty(required = true, value = "Displayable name of the Realm")
  public String getRealmName() {
    return realmName;
  }

  public EntityConcordanceV1 sourceEntityId(String sourceEntityId) {
    this.sourceEntityId = sourceEntityId;
    return this;
  }

   /**
   * Entity id of the source
   * @return sourceEntityId
  **/
  @ApiModelProperty(required = true, value = "Entity id of the source")
  public String getSourceEntityId() {
    return sourceEntityId;
  }

  public void setSourceEntityId(String sourceEntityId) {
    this.sourceEntityId = sourceEntityId;
  }

  public EntityConcordanceV1 sourceType(SourceTypeEnum sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Type of Source
   * @return sourceType
  **/
  @ApiModelProperty(example = "AMS360", required = true, value = "Type of Source")
  public SourceTypeEnum getSourceType() {
    return sourceType;
  }

  public void setSourceType(SourceTypeEnum sourceType) {
    this.sourceType = sourceType;
  }

  public EntityConcordanceV1 tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Id of the Tenant
   * @return tenantId
  **/
  @ApiModelProperty(example = "b647a79e-b500-4640-a1bf-2aeb2efef379", required = true, value = "Id of the Tenant")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityConcordanceV1 entityConcordanceV1 = (EntityConcordanceV1) o;
    return Objects.equals(this.entityId, entityConcordanceV1.entityId) &&
        Objects.equals(this.realmName, entityConcordanceV1.realmName) &&
        Objects.equals(this.sourceEntityId, entityConcordanceV1.sourceEntityId) &&
        Objects.equals(this.sourceType, entityConcordanceV1.sourceType) &&
        Objects.equals(this.tenantId, entityConcordanceV1.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, realmName, sourceEntityId, sourceType, tenantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityConcordanceV1 {\n");
    
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    realmName: ").append(toIndentedString(realmName)).append("\n");
    sb.append("    sourceEntityId: ").append(toIndentedString(sourceEntityId)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

