/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * IDPUserMetaDataV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class IDPUserMetaDataV1 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("lastLoginTime")
  private OffsetDateTime lastLoginTime = null;

   /**
   * Unique id of the AuthUser
   * @return id
  **/
  @ApiModelProperty(example = "b647a79e-b500-4640-a1bf-2aeb2efef379", value = "Unique id of the AuthUser")
  public String getId() {
    return id;
  }

   /**
   * Last time this user logged in
   * @return lastLoginTime
  **/
  @ApiModelProperty(example = "1970-01-01T00:00:00.000Z", value = "Last time this user logged in")
  public OffsetDateTime getLastLoginTime() {
    return lastLoginTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IDPUserMetaDataV1 idPUserMetaDataV1 = (IDPUserMetaDataV1) o;
    return Objects.equals(this.id, idPUserMetaDataV1.id) &&
        Objects.equals(this.lastLoginTime, idPUserMetaDataV1.lastLoginTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, lastLoginTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IDPUserMetaDataV1 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastLoginTime: ").append(toIndentedString(lastLoginTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

