/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LimitOffsetPagingInfoV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class LimitOffsetPagingInfoV1 {
  @SerializedName("method")
  private String method = null;

  @SerializedName("numberOfElements")
  private Integer numberOfElements = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("totalElements")
  private Integer totalElements = null;

  @SerializedName("totalPages")
  private Integer totalPages = null;

   /**
   * The method of paging that this pagingInfo contains
   * @return method
  **/
  @ApiModelProperty(value = "The method of paging that this pagingInfo contains")
  public String getMethod() {
    return method;
  }

   /**
   * The number of data elements in this response.
   * @return numberOfElements
  **/
  @ApiModelProperty(value = "The number of data elements in this response.")
  public Integer getNumberOfElements() {
    return numberOfElements;
  }

   /**
   * The page number of the response.
   * @return page
  **/
  @ApiModelProperty(value = "The page number of the response.")
  public Integer getPage() {
    return page;
  }

   /**
   * The page size of this response.
   * @return pageSize
  **/
  @ApiModelProperty(value = "The page size of this response.")
  public Integer getPageSize() {
    return pageSize;
  }

   /**
   * The total number of elements
   * @return totalElements
  **/
  @ApiModelProperty(value = "The total number of elements")
  public Integer getTotalElements() {
    return totalElements;
  }

   /**
   * The total number of pages, based on the pageSize and totalElements
   * @return totalPages
  **/
  @ApiModelProperty(value = "The total number of pages, based on the pageSize and totalElements")
  public Integer getTotalPages() {
    return totalPages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LimitOffsetPagingInfoV1 limitOffsetPagingInfoV1 = (LimitOffsetPagingInfoV1) o;
    return Objects.equals(this.method, limitOffsetPagingInfoV1.method) &&
        Objects.equals(this.numberOfElements, limitOffsetPagingInfoV1.numberOfElements) &&
        Objects.equals(this.page, limitOffsetPagingInfoV1.page) &&
        Objects.equals(this.pageSize, limitOffsetPagingInfoV1.pageSize) &&
        Objects.equals(this.totalElements, limitOffsetPagingInfoV1.totalElements) &&
        Objects.equals(this.totalPages, limitOffsetPagingInfoV1.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(method, numberOfElements, page, pageSize, totalElements, totalPages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LimitOffsetPagingInfoV1 {\n");
    
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

