/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import modelPackage.AddressV1;
import modelPackage.PhoneNumberV1;

/**
 * Location
 */
@ApiModel(description = "Location")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class LocationV1 {
  @SerializedName("addresses")
  private List<AddressV1> addresses = null;

  @SerializedName("phoneNumbers")
  private List<PhoneNumberV1> phoneNumbers = null;

  public LocationV1 addresses(List<AddressV1> addresses) {
    this.addresses = addresses;
    return this;
  }

  public LocationV1 addAddressesItem(AddressV1 addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<AddressV1>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * List of Addresses for the Location
   * @return addresses
  **/
  @ApiModelProperty(value = "List of Addresses for the Location")
  public List<AddressV1> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<AddressV1> addresses) {
    this.addresses = addresses;
  }

  public LocationV1 phoneNumbers(List<PhoneNumberV1> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public LocationV1 addPhoneNumbersItem(PhoneNumberV1 phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<PhoneNumberV1>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

   /**
   * List of Phone numbers for the Location
   * @return phoneNumbers
  **/
  @ApiModelProperty(value = "List of Phone numbers for the Location")
  public List<PhoneNumberV1> getPhoneNumbers() {
    return phoneNumbers;
  }

  public void setPhoneNumbers(List<PhoneNumberV1> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationV1 locationV1 = (LocationV1) o;
    return Objects.equals(this.addresses, locationV1.addresses) &&
        Objects.equals(this.phoneNumbers, locationV1.phoneNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, phoneNumbers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationV1 {\n");
    
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

