/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Standard Phone Number
 */
@ApiModel(description = "Standard Phone Number")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class PhoneNumberV1 {
  @SerializedName("countryCode")
  private String countryCode = null;

  @SerializedName("extension")
  private String extension = null;

  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  @SerializedName("preferred")
  private Boolean preferred = null;

  @SerializedName("type")
  private String type = null;

  public PhoneNumberV1 countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Country calling code
   * @return countryCode
  **/
  @ApiModelProperty(example = "1", value = "Country calling code")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public PhoneNumberV1 extension(String extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Extension number
   * @return extension
  **/
  @ApiModelProperty(example = "4567", value = "Extension number")
  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  public PhoneNumberV1 phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number
   * @return phoneNumber
  **/
  @ApiModelProperty(example = "5555555555", value = "Phone number")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public PhoneNumberV1 preferred(Boolean preferred) {
    this.preferred = preferred;
    return this;
  }

   /**
   * Indicates a preferred Phone Number
   * @return preferred
  **/
  @ApiModelProperty(example = "true", value = "Indicates a preferred Phone Number")
  public Boolean isPreferred() {
    return preferred;
  }

  public void setPreferred(Boolean preferred) {
    this.preferred = preferred;
  }

  public PhoneNumberV1 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of phone number
   * @return type
  **/
  @ApiModelProperty(example = "Cell Phone", value = "Type of phone number")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneNumberV1 phoneNumberV1 = (PhoneNumberV1) o;
    return Objects.equals(this.countryCode, phoneNumberV1.countryCode) &&
        Objects.equals(this.extension, phoneNumberV1.extension) &&
        Objects.equals(this.phoneNumber, phoneNumberV1.phoneNumber) &&
        Objects.equals(this.preferred, phoneNumberV1.preferred) &&
        Objects.equals(this.type, phoneNumberV1.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, extension, phoneNumber, preferred, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneNumberV1 {\n");
    
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    preferred: ").append(toIndentedString(preferred)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

