/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PhotoAddressV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class PhotoAddressV1 {
  @SerializedName("value")
  private String value = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("display")
  private String display = null;

  @SerializedName("preferred")
  private Boolean preferred = null;

   /**
   * Identifier, URI/address of the photo
   * @return value
  **/
  @ApiModelProperty(value = "Identifier, URI/address of the photo")
  public String getValue() {
    return value;
  }

   /**
   * A label indicating the photo&#39;s function
   * @return type
  **/
  @ApiModelProperty(example = "'photo' or 'thumbnail'", value = "A label indicating the photo's function")
  public String getType() {
    return type;
  }

   /**
   * A human-readable name, primarily used for display purposes.
   * @return display
  **/
  @ApiModelProperty(example = "My-Favority-Profile-Pic", value = "A human-readable name, primarily used for display purposes.")
  public String getDisplay() {
    return display;
  }

   /**
   * A Boolean value indicating the &#39;primary&#39; or preferred attribute value for this attribute, e.g., the preferred photo. The primary attribute value &#39;true&#39; MUST appear no more than once.
   * @return preferred
  **/
  @ApiModelProperty(example = "true", value = "A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred photo. The primary attribute value 'true' MUST appear no more than once.")
  public Boolean isPreferred() {
    return preferred;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhotoAddressV1 photoAddressV1 = (PhotoAddressV1) o;
    return Objects.equals(this.value, photoAddressV1.value) &&
        Objects.equals(this.type, photoAddressV1.type) &&
        Objects.equals(this.display, photoAddressV1.display) &&
        Objects.equals(this.preferred, photoAddressV1.preferred);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, type, display, preferred);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhotoAddressV1 {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    preferred: ").append(toIndentedString(preferred)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

