/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ProductV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class ProductV1 {
  @SerializedName("createdOn")
  private OffsetDateTime createdOn = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("updatedOn")
  private OffsetDateTime updatedOn = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("internal")
  private Boolean internal = null;

   /**
   * When the Product was created
   * @return createdOn
  **/
  @ApiModelProperty(value = "When the Product was created")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public ProductV1 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique, human-readable id of the Product
   * @return id
  **/
  @ApiModelProperty(example = "VERTAFORE", required = true, value = "Unique, human-readable id of the Product")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

   /**
   * When the Product was last modified
   * @return updatedOn
  **/
  @ApiModelProperty(value = "When the Product was last modified")
  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }

  public ProductV1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A human-readable name for the Product.
   * @return name
  **/
  @ApiModelProperty(example = "AMS360", required = true, value = "A human-readable name for the Product.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProductV1 internal(Boolean internal) {
    this.internal = internal;
    return this;
  }

   /**
   * Whether the Product is intended to be used internally
   * @return internal
  **/
  @ApiModelProperty(example = "false", required = true, value = "Whether the Product is intended to be used internally")
  public Boolean isInternal() {
    return internal;
  }

  public void setInternal(Boolean internal) {
    this.internal = internal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductV1 productV1 = (ProductV1) o;
    return Objects.equals(this.createdOn, productV1.createdOn) &&
        Objects.equals(this.id, productV1.id) &&
        Objects.equals(this.updatedOn, productV1.updatedOn) &&
        Objects.equals(this.name, productV1.name) &&
        Objects.equals(this.internal, productV1.internal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdOn, id, updatedOn, name, internal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductV1 {\n");
    
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    internal: ").append(toIndentedString(internal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

