/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * RealmV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class RealmV1 {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("updatedOn")
  private OffsetDateTime updatedOn = null;

  @SerializedName("createdOn")
  private OffsetDateTime createdOn = null;

  public RealmV1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Displayable name of the Realm
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Displayable name of the Realm")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RealmV1 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the Realm
   * @return description
  **/
  @ApiModelProperty(value = "Description of the Realm")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

   /**
   * When the Realm was last modified
   * @return updatedOn
  **/
  @ApiModelProperty(example = "1970-01-01T00:00:00.000Z", value = "When the Realm was last modified")
  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }

   /**
   * When the Realm was created
   * @return createdOn
  **/
  @ApiModelProperty(example = "1970-01-01T00:00:00.000Z", value = "When the Realm was created")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RealmV1 realmV1 = (RealmV1) o;
    return Objects.equals(this.name, realmV1.name) &&
        Objects.equals(this.description, realmV1.description) &&
        Objects.equals(this.updatedOn, realmV1.updatedOn) &&
        Objects.equals(this.createdOn, realmV1.createdOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, updatedOn, createdOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RealmV1 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

