/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * ServiceRoleV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class ServiceRoleV1 {
  @SerializedName("name")
  private String name = null;

  @SerializedName("serviceName")
  private String serviceName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("entitlements")
  private List<String> entitlements = null;

  @SerializedName("subServiceRoles")
  private Map<String, List<String>> subServiceRoles = null;

  @SerializedName("createdOn")
  private OffsetDateTime createdOn = null;

  @SerializedName("updatedOn")
  private OffsetDateTime updatedOn = null;

  public ServiceRoleV1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Provided display name, unique in combination with &#x60;serviceName&#x60;
   * @return name
  **/
  @ApiModelProperty(example = "admin", required = true, value = "Provided display name, unique in combination with `serviceName`")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ServiceRoleV1 serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Service to which this Service Role belongs
   * @return serviceName
  **/
  @ApiModelProperty(example = "example-service", required = true, value = "Service to which this Service Role belongs")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public ServiceRoleV1 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Brief description of this Service Role&#39;s purpose
   * @return description
  **/
  @ApiModelProperty(example = "Represents Admin Functionality", value = "Brief description of this Service Role's purpose")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ServiceRoleV1 entitlements(List<String> entitlements) {
    this.entitlements = entitlements;
    return this;
  }

  public ServiceRoleV1 addEntitlementsItem(String entitlementsItem) {
    if (this.entitlements == null) {
      this.entitlements = new ArrayList<String>();
    }
    this.entitlements.add(entitlementsItem);
    return this;
  }

   /**
   * List of Entitlements owned by this Service Role
   * @return entitlements
  **/
  @ApiModelProperty(example = "\"['example-service.user.delete', 'example-service.user.read']\"", value = "List of Entitlements owned by this Service Role")
  public List<String> getEntitlements() {
    return entitlements;
  }

  public void setEntitlements(List<String> entitlements) {
    this.entitlements = entitlements;
  }

  public ServiceRoleV1 subServiceRoles(Map<String, List<String>> subServiceRoles) {
    this.subServiceRoles = subServiceRoles;
    return this;
  }

  public ServiceRoleV1 putSubServiceRolesItem(String key, List<String> subServiceRolesItem) {
    if (this.subServiceRoles == null) {
      this.subServiceRoles = new HashMap<String, List<String>>();
    }
    this.subServiceRoles.put(key, subServiceRolesItem);
    return this;
  }

   /**
   * Map of service names to service role names for Service Roles owned by this Role.
   * @return subServiceRoles
  **/
  @ApiModelProperty(example = "\"{'example-service': ['admin'], 'other-example-service': ['viewThing', 'updateThing']}\"", value = "Map of service names to service role names for Service Roles owned by this Role.")
  public Map<String, List<String>> getSubServiceRoles() {
    return subServiceRoles;
  }

  public void setSubServiceRoles(Map<String, List<String>> subServiceRoles) {
    this.subServiceRoles = subServiceRoles;
  }

   /**
   * When the ServiceRole was created
   * @return createdOn
  **/
  @ApiModelProperty(example = "1970-01-01T00:00:00.000Z", value = "When the ServiceRole was created")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

   /**
   * When the ServiceRole was last modified
   * @return updatedOn
  **/
  @ApiModelProperty(example = "1970-01-01T00:00:00.000Z", value = "When the ServiceRole was last modified")
  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceRoleV1 serviceRoleV1 = (ServiceRoleV1) o;
    return Objects.equals(this.name, serviceRoleV1.name) &&
        Objects.equals(this.serviceName, serviceRoleV1.serviceName) &&
        Objects.equals(this.description, serviceRoleV1.description) &&
        Objects.equals(this.entitlements, serviceRoleV1.entitlements) &&
        Objects.equals(this.subServiceRoles, serviceRoleV1.subServiceRoles) &&
        Objects.equals(this.createdOn, serviceRoleV1.createdOn) &&
        Objects.equals(this.updatedOn, serviceRoleV1.updatedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, serviceName, description, entitlements, subServiceRoles, createdOn, updatedOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceRoleV1 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    entitlements: ").append(toIndentedString(entitlements)).append("\n");
    sb.append("    subServiceRoles: ").append(toIndentedString(subServiceRoles)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

