/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package modelPackage;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import modelPackage.AuthUserV1;

/**
 * UserAndAssignedRolesV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
public class UserAndAssignedRolesV1 {
  @SerializedName("roles")
  private Map<String, List<String>> roles = null;

  @SerializedName("user")
  private AuthUserV1 user = null;

  public UserAndAssignedRolesV1 roles(Map<String, List<String>> roles) {
    this.roles = roles;
    return this;
  }

  public UserAndAssignedRolesV1 putRolesItem(String key, List<String> rolesItem) {
    if (this.roles == null) {
      this.roles = new HashMap<String, List<String>>();
    }
    this.roles.put(key, rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public Map<String, List<String>> getRoles() {
    return roles;
  }

  public void setRoles(Map<String, List<String>> roles) {
    this.roles = roles;
  }

  public UserAndAssignedRolesV1 user(AuthUserV1 user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public AuthUserV1 getUser() {
    return user;
  }

  public void setUser(AuthUserV1 user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAndAssignedRolesV1 userAndAssignedRolesV1 = (UserAndAssignedRolesV1) o;
    return Objects.equals(this.roles, userAndAssignedRolesV1.roles) &&
        Objects.equals(this.user, userAndAssignedRolesV1.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roles, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAndAssignedRolesV1 {\n");
    
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

