/*
 * Authentication Service API
 * Authentication and Authorization
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package apiPackage;

import com.sun.jersey.api.client.GenericType;

import invokerPackage.ApiException;
import invokerPackage.ApiClient;
import invokerPackage.Configuration;
import modelPackage.*;
import invokerPackage.Pair;

import modelPackage.AuthGroupV1;
import modelPackage.EmptyResponseV1;
import modelPackage.PagedResponseV1AuthGroupV1LimitOffsetPagingInfoV1;
import modelPackage.SingleResponseV1AuthGroupV1;


  import java.util.ArrayList;
  import java.util.HashMap;
  import java.util.List;
  import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-02T00:57:29.075-06:00")
  public class GroupsApi {
  private ApiClient localVariablePrefixapiClient;

  public GroupsApi() {
  this(Configuration.getDefaultApiClient());
  }

  public GroupsApi(ApiClient apiClient) {
  this.localVariablePrefixapiClient = apiClient;
  }

  public ApiClient getApiClient() {
  return localVariablePrefixapiClient;
  }

  public void setApiClient(ApiClient apiClient) {
  this.localVariablePrefixapiClient = apiClient;
  }

    /**
    * Create AuthGroup
    * Create an AuthGroup within the Context provided
      * @param productId ID of the product for which the request is being made (required)
      * @param tenantId ID of the tenant for which the request is being made (required)
      * @param entityId ID of the entity for which the request is being made (required)
      * @param toBeCreated A new AuthGroup to be created (optional)
      * @return SingleResponseV1AuthGroupV1
    * @throws ApiException if fails to make API call
    */
    public SingleResponseV1AuthGroupV1 createAuthGroupUsingPOST(String productId, String tenantId, String entityId, AuthGroupV1 toBeCreated) throws ApiException {
    Object localVariablePrefixlocalVarPostBody = toBeCreated;
    
      // verify the required parameter 'productId' is set
      if (productId == null) {
      throw new ApiException(400, "Missing the required parameter 'productId' when calling createAuthGroupUsingPOST");
      }
    
      // verify the required parameter 'tenantId' is set
      if (tenantId == null) {
      throw new ApiException(400, "Missing the required parameter 'tenantId' when calling createAuthGroupUsingPOST");
      }
    
      // verify the required parameter 'entityId' is set
      if (entityId == null) {
      throw new ApiException(400, "Missing the required parameter 'entityId' when calling createAuthGroupUsingPOST");
      }
    
    // create path and map variables
    String localVariablePrefixlocalVarPath = "/auth/v1/{productId}/{tenantId}/entities/{entityId}/groups"
      .replaceAll("\\{" + "productId" + "\\}", localVariablePrefixapiClient.escapeString(productId.toString()))
      .replaceAll("\\{" + "tenantId" + "\\}", localVariablePrefixapiClient.escapeString(tenantId.toString()))
      .replaceAll("\\{" + "entityId" + "\\}", localVariablePrefixapiClient.escapeString(entityId.toString()));

    // query params
    List<Pair> localVariablePrefixlocalVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVariablePrefixlocalVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVariablePrefixlocalVarHeaderParams = new HashMap<String, String>();
    Map<String, Object> localVariablePrefixlocalVarFormParams = new HashMap<String, Object>();


    
    
      final String[] localVariablePrefixlocalVarAccepts = {
    "application/json"
      };
      final String localVariablePrefixlocalVarAccept = localVariablePrefixapiClient.selectHeaderAccept(localVariablePrefixlocalVarAccepts);

      final String[] localVariablePrefixlocalVarContentTypes = {
    "application/json"
      };
      final String localVariablePrefixlocalVarContentType = localVariablePrefixapiClient.selectHeaderContentType(localVariablePrefixlocalVarContentTypes);

      String[] localVariablePrefixlocalVarAuthNames = new String[] {  };

        GenericType<SingleResponseV1AuthGroupV1> localVariablePrefixlocalVarReturnType = new GenericType<SingleResponseV1AuthGroupV1>() {};
        return localVariablePrefixapiClient.invokeAPI(localVariablePrefixlocalVarPath, "POST", localVariablePrefixlocalVarQueryParams, localVariablePrefixlocalVarCollectionQueryParams, localVariablePrefixlocalVarPostBody, localVariablePrefixlocalVarHeaderParams, localVariablePrefixlocalVarFormParams, localVariablePrefixlocalVarAccept, localVariablePrefixlocalVarContentType, localVariablePrefixlocalVarAuthNames, localVariablePrefixlocalVarReturnType);
          }
    /**
    * Update or Create AuthGroup
    * Update or Create an AuthGroup specified by the Context provided
      * @param productId ID of the product for which the request is being made (required)
      * @param tenantId ID of the tenant for which the request is being made (required)
      * @param entityId ID of the entity for which the request is being made (required)
      * @param groupId ID of the AuthGroup (required)
      * @param toBeUpdated An AuthGroup to be updated or created (optional)
      * @return SingleResponseV1AuthGroupV1
    * @throws ApiException if fails to make API call
    */
    public SingleResponseV1AuthGroupV1 createOrUpdateAuthGroupUsingPUT(String productId, String tenantId, String entityId, String groupId, AuthGroupV1 toBeUpdated) throws ApiException {
    Object localVariablePrefixlocalVarPostBody = toBeUpdated;
    
      // verify the required parameter 'productId' is set
      if (productId == null) {
      throw new ApiException(400, "Missing the required parameter 'productId' when calling createOrUpdateAuthGroupUsingPUT");
      }
    
      // verify the required parameter 'tenantId' is set
      if (tenantId == null) {
      throw new ApiException(400, "Missing the required parameter 'tenantId' when calling createOrUpdateAuthGroupUsingPUT");
      }
    
      // verify the required parameter 'entityId' is set
      if (entityId == null) {
      throw new ApiException(400, "Missing the required parameter 'entityId' when calling createOrUpdateAuthGroupUsingPUT");
      }
    
      // verify the required parameter 'groupId' is set
      if (groupId == null) {
      throw new ApiException(400, "Missing the required parameter 'groupId' when calling createOrUpdateAuthGroupUsingPUT");
      }
    
    // create path and map variables
    String localVariablePrefixlocalVarPath = "/auth/v1/{productId}/{tenantId}/entities/{entityId}/groups/{groupId}"
      .replaceAll("\\{" + "productId" + "\\}", localVariablePrefixapiClient.escapeString(productId.toString()))
      .replaceAll("\\{" + "tenantId" + "\\}", localVariablePrefixapiClient.escapeString(tenantId.toString()))
      .replaceAll("\\{" + "entityId" + "\\}", localVariablePrefixapiClient.escapeString(entityId.toString()))
      .replaceAll("\\{" + "groupId" + "\\}", localVariablePrefixapiClient.escapeString(groupId.toString()));

    // query params
    List<Pair> localVariablePrefixlocalVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVariablePrefixlocalVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVariablePrefixlocalVarHeaderParams = new HashMap<String, String>();
    Map<String, Object> localVariablePrefixlocalVarFormParams = new HashMap<String, Object>();


    
    
      final String[] localVariablePrefixlocalVarAccepts = {
    "application/json"
      };
      final String localVariablePrefixlocalVarAccept = localVariablePrefixapiClient.selectHeaderAccept(localVariablePrefixlocalVarAccepts);

      final String[] localVariablePrefixlocalVarContentTypes = {
    "application/json"
      };
      final String localVariablePrefixlocalVarContentType = localVariablePrefixapiClient.selectHeaderContentType(localVariablePrefixlocalVarContentTypes);

      String[] localVariablePrefixlocalVarAuthNames = new String[] {  };

        GenericType<SingleResponseV1AuthGroupV1> localVariablePrefixlocalVarReturnType = new GenericType<SingleResponseV1AuthGroupV1>() {};
        return localVariablePrefixapiClient.invokeAPI(localVariablePrefixlocalVarPath, "PUT", localVariablePrefixlocalVarQueryParams, localVariablePrefixlocalVarCollectionQueryParams, localVariablePrefixlocalVarPostBody, localVariablePrefixlocalVarHeaderParams, localVariablePrefixlocalVarFormParams, localVariablePrefixlocalVarAccept, localVariablePrefixlocalVarContentType, localVariablePrefixlocalVarAuthNames, localVariablePrefixlocalVarReturnType);
          }
    /**
    * Delete AuthGroup
    * Delete an AuthGroup specified by the Context provided
      * @param productId ID of the product for which the request is being made (required)
      * @param tenantId ID of the tenant for which the request is being made (required)
      * @param entityId ID of the entity for which the request is being made (required)
      * @param groupId ID of AuthGroup to delete (required)
      * @return EmptyResponseV1
    * @throws ApiException if fails to make API call
    */
    public EmptyResponseV1 deleteAuthGroupUsingDELETE(String productId, String tenantId, String entityId, String groupId) throws ApiException {
    Object localVariablePrefixlocalVarPostBody = null;
    
      // verify the required parameter 'productId' is set
      if (productId == null) {
      throw new ApiException(400, "Missing the required parameter 'productId' when calling deleteAuthGroupUsingDELETE");
      }
    
      // verify the required parameter 'tenantId' is set
      if (tenantId == null) {
      throw new ApiException(400, "Missing the required parameter 'tenantId' when calling deleteAuthGroupUsingDELETE");
      }
    
      // verify the required parameter 'entityId' is set
      if (entityId == null) {
      throw new ApiException(400, "Missing the required parameter 'entityId' when calling deleteAuthGroupUsingDELETE");
      }
    
      // verify the required parameter 'groupId' is set
      if (groupId == null) {
      throw new ApiException(400, "Missing the required parameter 'groupId' when calling deleteAuthGroupUsingDELETE");
      }
    
    // create path and map variables
    String localVariablePrefixlocalVarPath = "/auth/v1/{productId}/{tenantId}/entities/{entityId}/groups/{groupId}"
      .replaceAll("\\{" + "productId" + "\\}", localVariablePrefixapiClient.escapeString(productId.toString()))
      .replaceAll("\\{" + "tenantId" + "\\}", localVariablePrefixapiClient.escapeString(tenantId.toString()))
      .replaceAll("\\{" + "entityId" + "\\}", localVariablePrefixapiClient.escapeString(entityId.toString()))
      .replaceAll("\\{" + "groupId" + "\\}", localVariablePrefixapiClient.escapeString(groupId.toString()));

    // query params
    List<Pair> localVariablePrefixlocalVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVariablePrefixlocalVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVariablePrefixlocalVarHeaderParams = new HashMap<String, String>();
    Map<String, Object> localVariablePrefixlocalVarFormParams = new HashMap<String, Object>();


    
    
      final String[] localVariablePrefixlocalVarAccepts = {
    "application/json"
      };
      final String localVariablePrefixlocalVarAccept = localVariablePrefixapiClient.selectHeaderAccept(localVariablePrefixlocalVarAccepts);

      final String[] localVariablePrefixlocalVarContentTypes = {
    "application/json"
      };
      final String localVariablePrefixlocalVarContentType = localVariablePrefixapiClient.selectHeaderContentType(localVariablePrefixlocalVarContentTypes);

      String[] localVariablePrefixlocalVarAuthNames = new String[] {  };

        GenericType<EmptyResponseV1> localVariablePrefixlocalVarReturnType = new GenericType<EmptyResponseV1>() {};
        return localVariablePrefixapiClient.invokeAPI(localVariablePrefixlocalVarPath, "DELETE", localVariablePrefixlocalVarQueryParams, localVariablePrefixlocalVarCollectionQueryParams, localVariablePrefixlocalVarPostBody, localVariablePrefixlocalVarHeaderParams, localVariablePrefixlocalVarFormParams, localVariablePrefixlocalVarAccept, localVariablePrefixlocalVarContentType, localVariablePrefixlocalVarAuthNames, localVariablePrefixlocalVarReturnType);
          }
    /**
    * Get AuthGroup
    * Retrieves an AuthGroup
      * @param productId ID of the product for which the request is being made (required)
      * @param tenantId ID of the tenant for which the request is being made (required)
      * @param entityId ID of the entity for which the request is being made (required)
      * @param groupId ID of the AuthGroup (required)
      * @return SingleResponseV1AuthGroupV1
    * @throws ApiException if fails to make API call
    */
    public SingleResponseV1AuthGroupV1 getAuthGroupUsingGET(String productId, String tenantId, String entityId, String groupId) throws ApiException {
    Object localVariablePrefixlocalVarPostBody = null;
    
      // verify the required parameter 'productId' is set
      if (productId == null) {
      throw new ApiException(400, "Missing the required parameter 'productId' when calling getAuthGroupUsingGET");
      }
    
      // verify the required parameter 'tenantId' is set
      if (tenantId == null) {
      throw new ApiException(400, "Missing the required parameter 'tenantId' when calling getAuthGroupUsingGET");
      }
    
      // verify the required parameter 'entityId' is set
      if (entityId == null) {
      throw new ApiException(400, "Missing the required parameter 'entityId' when calling getAuthGroupUsingGET");
      }
    
      // verify the required parameter 'groupId' is set
      if (groupId == null) {
      throw new ApiException(400, "Missing the required parameter 'groupId' when calling getAuthGroupUsingGET");
      }
    
    // create path and map variables
    String localVariablePrefixlocalVarPath = "/auth/v1/{productId}/{tenantId}/entities/{entityId}/groups/{groupId}"
      .replaceAll("\\{" + "productId" + "\\}", localVariablePrefixapiClient.escapeString(productId.toString()))
      .replaceAll("\\{" + "tenantId" + "\\}", localVariablePrefixapiClient.escapeString(tenantId.toString()))
      .replaceAll("\\{" + "entityId" + "\\}", localVariablePrefixapiClient.escapeString(entityId.toString()))
      .replaceAll("\\{" + "groupId" + "\\}", localVariablePrefixapiClient.escapeString(groupId.toString()));

    // query params
    List<Pair> localVariablePrefixlocalVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVariablePrefixlocalVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVariablePrefixlocalVarHeaderParams = new HashMap<String, String>();
    Map<String, Object> localVariablePrefixlocalVarFormParams = new HashMap<String, Object>();


    
    
      final String[] localVariablePrefixlocalVarAccepts = {
    "application/json"
      };
      final String localVariablePrefixlocalVarAccept = localVariablePrefixapiClient.selectHeaderAccept(localVariablePrefixlocalVarAccepts);

      final String[] localVariablePrefixlocalVarContentTypes = {
    "application/json"
      };
      final String localVariablePrefixlocalVarContentType = localVariablePrefixapiClient.selectHeaderContentType(localVariablePrefixlocalVarContentTypes);

      String[] localVariablePrefixlocalVarAuthNames = new String[] {  };

        GenericType<SingleResponseV1AuthGroupV1> localVariablePrefixlocalVarReturnType = new GenericType<SingleResponseV1AuthGroupV1>() {};
        return localVariablePrefixapiClient.invokeAPI(localVariablePrefixlocalVarPath, "GET", localVariablePrefixlocalVarQueryParams, localVariablePrefixlocalVarCollectionQueryParams, localVariablePrefixlocalVarPostBody, localVariablePrefixlocalVarHeaderParams, localVariablePrefixlocalVarFormParams, localVariablePrefixlocalVarAccept, localVariablePrefixlocalVarContentType, localVariablePrefixlocalVarAuthNames, localVariablePrefixlocalVarReturnType);
          }
    /**
    * Get AuthGroups
    * Retrieves all AuthGroups for given Context
      * @param productId ID of the product for which the request is being made (required)
      * @param tenantId ID of the tenant for which the request is being made (required)
      * @param entityId ID of the entity for which the request is being made (required)
      * @param pageSize The maximum number of items to include in the response (optional)
      * @param page The page of items to retrieve (optional)
      * @return PagedResponseV1AuthGroupV1LimitOffsetPagingInfoV1
    * @throws ApiException if fails to make API call
    */
    public PagedResponseV1AuthGroupV1LimitOffsetPagingInfoV1 getAuthGroupUsingGET1(String productId, String tenantId, String entityId, Integer pageSize, Integer page) throws ApiException {
    Object localVariablePrefixlocalVarPostBody = null;
    
      // verify the required parameter 'productId' is set
      if (productId == null) {
      throw new ApiException(400, "Missing the required parameter 'productId' when calling getAuthGroupUsingGET1");
      }
    
      // verify the required parameter 'tenantId' is set
      if (tenantId == null) {
      throw new ApiException(400, "Missing the required parameter 'tenantId' when calling getAuthGroupUsingGET1");
      }
    
      // verify the required parameter 'entityId' is set
      if (entityId == null) {
      throw new ApiException(400, "Missing the required parameter 'entityId' when calling getAuthGroupUsingGET1");
      }
    
    // create path and map variables
    String localVariablePrefixlocalVarPath = "/auth/v1/{productId}/{tenantId}/entities/{entityId}/groups{?pageSize,page}"
      .replaceAll("\\{" + "productId" + "\\}", localVariablePrefixapiClient.escapeString(productId.toString()))
      .replaceAll("\\{" + "tenantId" + "\\}", localVariablePrefixapiClient.escapeString(tenantId.toString()))
      .replaceAll("\\{" + "entityId" + "\\}", localVariablePrefixapiClient.escapeString(entityId.toString()));

    // query params
    List<Pair> localVariablePrefixlocalVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVariablePrefixlocalVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVariablePrefixlocalVarHeaderParams = new HashMap<String, String>();
    Map<String, Object> localVariablePrefixlocalVarFormParams = new HashMap<String, Object>();

      localVariablePrefixlocalVarQueryParams.addAll(localVariablePrefixapiClient.parameterToPair("pageSize", pageSize));
      localVariablePrefixlocalVarQueryParams.addAll(localVariablePrefixapiClient.parameterToPair("page", page));

    
    
      final String[] localVariablePrefixlocalVarAccepts = {
    "application/json"
      };
      final String localVariablePrefixlocalVarAccept = localVariablePrefixapiClient.selectHeaderAccept(localVariablePrefixlocalVarAccepts);

      final String[] localVariablePrefixlocalVarContentTypes = {
    "application/json"
      };
      final String localVariablePrefixlocalVarContentType = localVariablePrefixapiClient.selectHeaderContentType(localVariablePrefixlocalVarContentTypes);

      String[] localVariablePrefixlocalVarAuthNames = new String[] {  };

        GenericType<PagedResponseV1AuthGroupV1LimitOffsetPagingInfoV1> localVariablePrefixlocalVarReturnType = new GenericType<PagedResponseV1AuthGroupV1LimitOffsetPagingInfoV1>() {};
        return localVariablePrefixapiClient.invokeAPI(localVariablePrefixlocalVarPath, "GET", localVariablePrefixlocalVarQueryParams, localVariablePrefixlocalVarCollectionQueryParams, localVariablePrefixlocalVarPostBody, localVariablePrefixlocalVarHeaderParams, localVariablePrefixlocalVarFormParams, localVariablePrefixlocalVarAccept, localVariablePrefixlocalVarContentType, localVariablePrefixlocalVarAuthNames, localVariablePrefixlocalVarReturnType);
          }
    }
